require(ez)
setwd('/Users/jnirody/Documents/Dropbox/Research/geckos/Data/Sorted Data used for Anlysis')
data = read.csv('scaled values.csv')


# get all descriptive stats
ezStats(data=data,dv=fl.height,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=fl.slap.vel,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=fl.stroke.vel,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=bl.height,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=bl.slap.vel,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=bl.stroke.vel,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=stance,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=swing,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=period,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=vel,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=head.ht,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=fl.slap.imp,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=fl.stroke.ver.imp,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=fl.stroke.hor.imp,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=bl.slap.imp,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=bl.stroke.ver.imp,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=bl.stroke.hor.imp,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=Est.impulse,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=min.imp,wid=geckoID,between=expt,type=2)
ezStats(data=data,dv=imp.percent,wid=geckoID,between=expt,type=2)

# do all comparisons
ezANOVA(data=data,dv=fl.height,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=fl.slap.vel,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=fl.stroke.vel,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=bl.height,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=bl.slap.vel,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=bl.stroke.vel,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=stance,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=swing,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=period,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=vel,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=head.ht,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=fl.slap.imp,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=fl.stroke.imp,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=bl.slap.imp,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=bl.stroke.imp,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=Est.impluse,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=min.imp,wid=geckoID,between=expt,type=2)
ezANOVA(data=data,dv=imp.percent,wid=geckoID,between=expt,type=2)